- hosts: all
  gather_facts: False
  roles:
      - pythondeps

- hosts: all
  become: yes
  roles:
      - selinux
      - ntp
      - mariadb
      - mongo
      - nginx
      - rabbitmq
      - phantomjs
      - dashboard.user
      - dashboard.app
      - supervisor
