- hosts: all
  gather_facts: False
  roles:
      - pythondeps

- hosts: all
  become: yes
  pre_tasks:
      - include_vars: vars/secrets.yml
  roles:
      - selinux
      - ntp
      - mariadb
      - mongo
      - nginx
      - rabbitmq
      - phantomjs
      - dashboard.user
      - dashboard.app
      - supervisor
