- package:
    name: "{{ item }}"
    state: latest
  with_items:
      - mongo-tools
      - mongodb-server
      - mongodb
  notify:
      - mongo_restart

- service:
    name: mongod
    enabled: True
    state: started
